service: order-processing

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  createOrder:
    handler: src/functions/orders/createOrder.handler
    events:
      - http:
          path: orders
          method: post

  processOrder:
    handler: src/functions/orders/processOrder.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - OrdersTable
              - StreamArn

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

plugins:
  - serverless-offline